##############################################################################
################################# makefile ###################################
##############################################################################
#		                                                             #
#   makefile of MMCFClass	                                             #
#				                                             #
#   Input:  $(MMFDIR) = the directory where the source is                    #
#									     #
#   Output: $(MMFH)   = the .h files to include				     #
#           $(MMFINC) = the -I$(include directories)			     #
#									     #
#                                VERSION 1.00				     #
#                	        09 - 05 - 2012				     #
#									     #
#			      Antonio Frangioni				     #
#   			   Operations Research Group			     #
#			  Dipartimento di Informatica			     #
#   			     Universita' di Pisa			     #
#									     #
##############################################################################

MMFINC = -I$(MMFDIR)
MMFH = $(MMFDIR)MMCFClas.h

############################ End of makefile #################################
