CNDSM: PrimalDual Class Reference
PrimalDual Class Reference
Definition of the class PrimalDual.
#include <PrimalDual.h>
Public Member Functions
PrimalDual (SubGrad *slvr, istream *iStrm=0)
Constructor of the class, which derives from both Deflection and Stepsize.
Other initializations
void SetVOLLog (ostream *outs=0, const char lvl=0)
void Format (void)
Reading the solution
void NewDEF (void)
The variant requires thats DR must be computed before SR.
void NewStep (void)
cHpNum GetDFLCoeff (void)
HpNum GetStepsize (bool StepIsIncr=false)
HpNum GetLev (void)
HpNum GetBeta (void)
void SetMaxBeta (const HpNum alpha)
Public Member Functions inherited from Deflection
Deflection (SubGrad *slvr)
Constructor of the class.
virtual const bool DoSS (void)
Returns true if a Serious Step (SS) takes place.
virtual cHpNum Delta (void)
Returns the expected improvement in the objective function [see DoSS()].
virtual ~Deflection ()
Public Member Functions inherited from Stepsize
Stepsize (SubGrad *slvr, istream *iStrm=0)
Constructor of the class.
Stepsize (SubGrad *slvr, istream *iStrm=0)
Constructor of the class.
virtual void SetSTPLog (ostream *outs=0, const char lvl=0)
The class outputs "log" information onto the ostream pointed by outs.
virtual void SetSTPLog (ostream *outs=0, const char lvl=0)
The class outputs "log" information onto the ostream pointed by outs.
virtual bool NeedsdkM1Gk (void)
Returns true if the stepsize requires the scalar product .
virtual bool NeedsdkM1Gk (void)
Returns true if the stepsize requires the scalar product .
virtual ~Stepsize ()
virtual ~Stepsize ()
Additional Inherited Members
Protected Member Functions inherited from Deflection
FiOracle * GetOracle (void)
Returns the pointer to FiOracle.
HpNum GetStepsize (void)
Returns the stepsize .
cHpNum GetGiNorm (void)
Returns the norm of the subgradient .
cHpNum GetDNorm (void)
Returns the norm of the direction .
cHpNum GetdGk (void)
Returns the scalar product .
cHpNum GetSigma (void)
Returns the linearization error .
cHpNum GetEpsilon (void)
Returns the linearization error .
cHpNum ReadFVal (void)
Returns the full function .
Protected Member Functions inherited from Stepsize
virtual bool UpdateTargetLevel (void)
It tries to provide a new target level .
virtual bool UpdateTargetLevel (void)
It tries to provide a new target level .
HpNum GetCoeffDefl (void)
Returns the deflection coefficient .
FiOracle * GetOracle (void)
Returns the pointer to FiOracle.
cHpNum GetGiNorm (void)
Returns the norm of the subgradient .
cHpNum GetDNorm (void)
Returns the norm of the direction .
cHpNum GetdGk (void)
Returns the scalar product .
HpNum GetdkM1Gk (void)
Returns the scalar product .
Index GetNItIcr (void)
Returns NItIncr, the parameter for incremental iterations [see SubGrad.h].
cHpNum ReadFkVal (void)
Returns FiLambda [ see SubGrad.h ].
cHpNum ReadFiBar (void)
Returns FiBar [ see SubGrad.h ].
HpNum GetCoeffDefl (void)
Returns the deflection coefficient .
FiOracle * GetOracle (void)
Returns the pointer to FiOracle.
cHpNum GetGiNorm (void)
Returns the norm of the subgradient .
cHpNum GetDNorm (void)
Returns the norm of the direction .
cHpNum GetdGk (void)
Returns the scalar product .
HpNum GetdkM1Gk (void)
Returns the scalar product .
Index GetNItIcr (void)
Returns NItIncr, the parameter for incremental iterations [see SubGrad.h].
cHpNum ReadFkVal (void)
Returns FiLambda [ see SubGrad.h ].
cHpNum ReadFiBar (void)
Returns FiBar [ see SubGrad.h ].
Protected Attributes inherited from Deflection
SubGrad * Solver
(pointer to) the SubGrad solver
ostream * VOLLog
the output stream object
char VOLLLvl
the "level of verbosity"
Protected Attributes inherited from Stepsize
SubGrad * Solver
(pointer to) the SubGrad solver
ostream * STPLog
the output stream object
char STPLLvl
the "level of verbosity"
HpNum FiLev
the target level
HpNum Beta
beta factor
HpNum MaxBeta
maximum value for beta factor
HpNum LpsFct
scaling factor
Detailed Description
Definition of the class PrimalDual.
This class implements two variants of the Primal-Dual subgradient method (PDSM): simple and weighted averages, under a unified SM scheme. The method has a fixed stability center, and the direction can be regarded as the average of all the previous weighted subgradients, i.e.:
It is worth mentioning that the subgradient weights can be non-vanishing as . The stepsize rule (SR) and the deflection rule (DR), respectively, are:
where is chosen in a suitable way.
Constructor & Destructor Documentation
PrimalDual (SubGrad * slvr, istream * iStrm = 0) inline
Constructor of the class, which derives from both Deflection and Stepsize.
Since the constructor of PrimalDual is executed after the one of Stepsize, the following parameters specific for PrimalDual have to be found in the stream after those of the base class Stepsize [see the comments to the constructor of Stepsize]:
bool average [true] if true simple averages are used, otherwise weighted averages are used
For this class, the general parameter LpsFct -defined in Stepsize.h- represents the gamma factor F used to set .
References Deflection::Format(), FiOracle::GetGlobalLipschitz(), Deflection::GetOracle(), Deflection::GetStepsize(), Stepsize::LpsFct, Deflection::SetVOLLog(), Deflection::VOLLLvl, and Deflection::VOLLog.
Member Function Documentation
void NewDEF (void) inline virtual
The variant requires thats DR must be computed before SR.
Hence, the call to NewDEF comes before the one to NewStep.
Implements Deflection.
References Deflection::GetGiNorm(), Stepsize::LpsFct, and Deflection::Solver.