CNDSM: FumeroTV Class Reference
FumeroTV Class Reference
Definition of the class FumeroTV.
#include <FumeroTV.h>
Public Member Functions
Constructor
FumeroTV (SubGrad *slvr, istream *iStrm=NULL)
Constructor of the class.
Other initializations
void SetSTPLog (ostream *outs=0, const char lvl=0)
void Format (void)
Computing the stepsize
void NewStep (void)
Public Member Functions inherited from Stepsize
Stepsize (SubGrad *slvr, istream *iStrm=0)
Constructor of the class.
Stepsize (SubGrad *slvr, istream *iStrm=0)
Constructor of the class.
virtual bool NeedsdkM1Gk (void)
Returns true if the stepsize requires the scalar product .
virtual bool NeedsdkM1Gk (void)
Returns true if the stepsize requires the scalar product .
virtual HpNum GetStepsize (bool StepIsIncr=false)
This function must be called after NewStep() [see above].
virtual HpNum GetLev (void)
This function must be called after NewStep() [see above].
virtual HpNum GetBeta (void)
This function must be called after NewStep() [see above].
virtual HpNum GetStepsize (bool StepIsIncr=false)
This function must be called after NewStep() [see above].
virtual HpNum GetLev (void)
This function must be called after NewStep() [see above].
virtual HpNum GetBeta (void)
This function must be called after NewStep() [see above].
virtual void SetMaxBeta (const HpNum alpha)
Changes the maximum value of for a target value stepsize rule.
virtual void SetMaxBeta (const HpNum alpha)
Changes the maximum value of for a target value stepsize rule.
virtual ~Stepsize ()
virtual ~Stepsize ()
Additional Inherited Members
Protected Member Functions inherited from Stepsize
HpNum GetCoeffDefl (void)
Returns the deflection coefficient .
FiOracle * GetOracle (void)
Returns the pointer to FiOracle.
cHpNum GetGiNorm (void)
Returns the norm of the subgradient .
cHpNum GetDNorm (void)
Returns the norm of the direction .
cHpNum GetdGk (void)
Returns the scalar product .
HpNum GetdkM1Gk (void)
Returns the scalar product .
Index GetNItIcr (void)
Returns NItIncr, the parameter for incremental iterations [see SubGrad.h].
cHpNum ReadFkVal (void)
Returns FiLambda [ see SubGrad.h ].
cHpNum ReadFiBar (void)
Returns FiBar [ see SubGrad.h ].
HpNum GetCoeffDefl (void)
Returns the deflection coefficient .
FiOracle * GetOracle (void)
Returns the pointer to FiOracle.
cHpNum GetGiNorm (void)
Returns the norm of the subgradient .
cHpNum GetDNorm (void)
Returns the norm of the direction .
cHpNum GetdGk (void)
Returns the scalar product .
HpNum GetdkM1Gk (void)
Returns the scalar product .
Index GetNItIcr (void)
Returns NItIncr, the parameter for incremental iterations [see SubGrad.h].
cHpNum ReadFkVal (void)
Returns FiLambda [ see SubGrad.h ].
cHpNum ReadFiBar (void)
Returns FiBar [ see SubGrad.h ].
Protected Attributes inherited from Stepsize
SubGrad * Solver
(pointer to) the SubGrad solver
ostream * STPLog
the output stream object
char STPLLvl
the "level of verbosity"
HpNum FiLev
the target level
HpNum Beta
beta factor
HpNum MaxBeta
maximum value for beta factor
HpNum LpsFct
scaling factor
Detailed Description
Definition of the class FumeroTV.
This class implements a target value stepsize. At the beginning is set to the given lower bound and exponentially goes towards . The method works in two phases. In the first one is decremented, while in the second one is still decremented but also incremented after a pre-set number of consecutive improving iterations.
Constructor & Destructor Documentation
FumeroTV (SubGrad * slvr, istream * iStrm = NULL) inline
Constructor of the class.
Since the constructor of FumeroTV is executed after the one of Stepsize, the following parameters specific for the FumeroTV have to be found in the stream after those of the base class [see the comments to the constructor of Stepsize]:
HpNum sigmaMin [ 1e-4 ] tolerance of the function
Index r1 [ 2 ] sigma_{r1} = 1/2
HpNum beta0 [ 1 ] initial value of beta
Index eta1 [ 10 ] threshold on number of failures (phase I)
index eta2 [ 10 ] threshold on number of failures (phase II)
References Stepsize::Beta, Stepsize::FiLev, Stepsize::Format(), FiOracle::GetLowerBound(), Stepsize::GetOracle(), Stepsize::ReadFkVal(), Stepsize::SetSTPLog(), Stepsize::STPLLvl, and Stepsize::STPLog.