##############################################################################
################################# makefile ###################################
##############################################################################
#                                                                            #
#   makefile of CQKnPClass                                                   #
#                                                                            #
#   Input:  $(CQKDIR) = the directory where the source is                    #
#                                                                            #
#   Output: $(CQKH)   = the .h files to include                              #
#           $(CQKINC) = the -I$(include directories)                         #
#                                                                            #
#                                VERSION 1.00	                             #
#                                17 - 05 - 2012                              #
#                                                                            #
#                              Antonio Frangioni                             #
#                            Operations Research Group                       #
#                           Dipartimento di Informatica	                     #
#                            Universita' di Pisa                             #
#                                                                            #
##############################################################################

# macroes to be exported- - - - - - - - - - - - - - - - - - - - - - - - - - -

CQKH = $(CQKDIR)CQKnPClass.h
CQKINC = -I$(CQKDIR)

############################ End of makefile #################################
